### PR TITLE
Prevent merging interfaces with same name in different modules

### PR DESCRIPTION
**Pull request by goodmind**
Follow-up to previous PR

### CODE REVIEW

**Comment by orta** [comment]
Cool, yeah, looks good to me 👍

**Comment by goodmind** [comment]
@orta did you publish latest release? something wrong with lib folder

**Comment by orta** [comment]
Wanna try 1.5.3? Think I got it

**Comment by goodmind** [comment]
@orta still old lib

**Comment by goodmind** [comment]
> Files included with the “package.json#files” field cannot be excluded through .npmignore or .gitignore.

**Pull request merged**
