### PR TITLE
Support optional methods and import/export as

### PR DESCRIPTION
**Pull request by goodmind**
It's unfortunate that there isn't one huge .d.ts with all TypeScript features :\\
I didn't knew that typescript have different syntax for optional methods
```ts
interface Example<State> {
  optional?<R>(value: any, state: State): any;
}
```

### CODE REVIEW

**Comment by orta** [comment]
Yep, cool

**Comment by orta** [comment]
Yeah, the closest I know is the big AST list inside typescript somewhere - but that's too low level to be of use

**Comment by orta** [comment]
Shipped as 1.5.6

**Comment by goodmind** [comment]
@orta too fast

**Pull request merged**
