### PR TITLE
Folder convert support

### PR DESCRIPTION
**Pull request by goodmind**
```sh
flowgen path/to/folder
```
would convert all of `.d.ts` files in this folder to `.js.flow` files in `exports` folder
`// @flow` header would be added automatically

```sh
flowgen path/to/folder --flow-typed-format
```
Doesn't affect output folder (still `exports`)

```sh
flowgen path/to/folder --out filename.js
```
Doesn't affect output folder (still `exports`)

```sh
flowgen path/to/folder --add-flow-header
```
Doesn't affect output files

### CODE REVIEW

**Comment by orta** [comment]
Looks like some node 6 issues, II'm also happy to bump the supported version too?

**Comment by goodmind** [comment]
@orta should flowgen target LTS or lower?

**Comment by goodmind** [comment]
@orta ping

**Comment by orta** [comment]
Thanks, sorry, LTS seems fine for me?

**Comment by orta** [comment]
Cool, looks good - shipping

**Pull request merged**
