### PR TITLE
Typecheck (BREAKING CHANGES)

### PR DESCRIPTION
**Pull request by goodmind**
Probably experimental and shouldn't be merged?

## CLI

- Add `--no-module-exports` options, it disables `declare module.exports` syntax in favor of `declare export default`
- Add `--flow-typed-export [folder]` instead of exporting to `../exports` folder, it now exports to `./exports` and you can change folder name
- Remove `--string-enums` flag

## Compiler (breaking change?)

- Use TypeScript typechecker for name resolving 

## Parser

- Use transformers to remove legacy syntax with new

   - **ImportEqualsTransformer**
      Replace `import x = require('y')` with `import * as x from 'y'`

   - **LegacyModules**
      Replace `module Identifier {}` with `namespace Identifier {}`
      (don't confuse with `declare module 'package-name' {}`)

- Use recursive `addChildren` for nested namespaces
- Print enums, classes, and nested namespaces identifiers inside namespaces
- Use `Symbol.for('nodejs.util.inspect')` for printing nodes in console instead of cloning them

## Printers

- Print empty line for `import 'side-effect'` in `declare module`
- Move `literalType` printer
- Move `typeParameter` printer
- Move `propertyDeclaration` printer
- Replace class enums with simplified object enums, resolve enum and enum members references with typechecker
- Qualify identifiers inside `class` and `interface` (resolve namespaces)
- Add support for unnamed default export
   `export default function(): void;`
- Add support for renaming module identifiers (**@types/react** should be installed)

<table>
<tr>
<td align="center">
<b>From</b>
</td>
<td align="center">
<b>To<b>
</td>
</tr>
<tr>
<td>

  ```ts
  import * as React from 'react'
  type S = React.ReactNode
  ```
</td>
<td>

  ```js
  import * as React from 'react'
  type S = React.Node
  ```
</td>
</tr>
<tr>
<td>

  ```ts
  import {ReactNode} from 'react'
  type S = ReactNode
  ```
</td>
<td>

  ```js
  import type {Node} from 'react'
  type S = Node
  ```
</td>
</tr>
</table>

- Error on BigInt (I actually added parsing of BigInts to Flow in https://github.com/facebook/flow/pull/7471)

- Error on `unique symbol`

- Convert `typeof import('module')` type to `$Exports<'module'>`

### CODE REVIEW

**Comment by orta** [comment]
If it's useful, I'm fine with bumping this lib in major semver for it?

**Comment by goodmind** [comment]
@orta, yeah, probably would be ok

**Comment by goodmind** [comment]
@orta anything preventing merging this?

**Comment by orta** [comment]
Nope, just me coming back and merging it :D

**Comment by orta** [comment]
OK, shipped as 1,6,0

**Comment by goodmind** [comment]
@orta do you mind if I had rights to commit and label issues directly in this repo?

**Comment by orta** [comment]
[I'd prefer it](https://github.com/Moya/contributors#moya-community-continuity-guidelines-v200), but I don't have access to give to that access I'm afraid

**Comment by FezVrasta** [comment]
Was this ever released? `--flow-typed-export` tells me it's not a valid option.

**Comment by ozyman42** [comment]
Use `--flow-typed-format` instead of `--flow-typed-export`

**Pull request merged**
